# Nome do workflow
name: nbQA

# Definindo os eventos que acionarão este workflow
on:
  # Quando houver um push no repositório
  push:
    # Somente para arquivos com extensão .ipynb
    paths:
      - '**.ipynb'
  # Quando houver uma solicitação de pull no repositório
  pull_request:
    # Somente para arquivos com extensão .ipynb
    paths:
      - '**.ipynb'

# Definindo os jobs que serão executados
jobs:
  # Nome do job
  nbqa-check:
    # Definindo o sistema operacional onde o job será executado
    runs-on: ubuntu-latest
    # Definindo as etapas do job
    steps:
    # Etapa para obter o código do repositório
    - name: Check out code
      uses: actions/checkout@v2

    # Etapa para configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Etapa para instalar as dependências necessárias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbqa isort pyupgrade ruff black
    
    # Identificar os arquivos .ipynb modificados no último commit
    - name: Get changed notebooks
      id: getfile
      run:
      # Armazenar os nomes dos arquivos modificados na variável CHANGED_FILES
        echo "CHANGED_FILES=$(git diff --name-only --diff-filter=AM HEAD~1 HEAD | grep .ipynb)" >> $GITHUB_ENV
    
    - name: Debug - Print changed files
      run: |
        echo "Changed files: $CHANGED_FILES"

    # Etapa para executar o isort nos notebooks
    - name: Run nbQA with isort
      run:
        nbqa isort "$CHANGED_FILES"

    # Etapa para executar o pyupgrade nos notebooks
    - name: Run nbQA with pyupgrade
      run:
        nbqa pyupgrade $CHANGED_FILES
      # Continuar mesmo se houver erro
      continue-on-error: true

    # Etapa para executar o black nos notebooks
    - name: Run nbQA with black
      run:
        nbqa black $CHANGED_FILES --line-length 120

    # Etapa para executar o ruff nos notebooks
    - name: Run nbQA with ruff
      run:
        nbqa ruff $CHANGED_FILES --ignore=E203,E266,E402,E501

    # Etapa para verificar se houve modificações nos arquivos
    - name: Check for modified files
      id: git-check
      run: |
        git diff --exit-code || echo "files-changed=yes" >> $GITHUB_ENV

    # Etapa para configurar a identidade do Git
    - name: Set Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Etapa para fazer commit e push das alterações, se houver
    - name: Commit and push changes (if any)
      if: env.files-changed == 'yes'
      run: |
        git add -A
        git commit -m "Automatically formatted by nbQA"
        git push
