name: nbQA

on:
  push:
    paths:
      - '**.ipynb'
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  nbqa-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbqa flake8 black isort
    - name: Run nbQA with isort, black, and flake8
      run: |
        nbqa isort *.ipynb
        nbqa black *.ipynb
        nbqa flake8 *.ipynb
    - name: Check for modified files
      id: git-check
      run: |
        git diff --exit-code || echo "files-changed=yes" >> $GITHUB_ENV
    - name: Set Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Commit and push changes (if any)
      if: env.files-changed == 'yes'
      run: |
        git add -A
        git commit -m "Automatically formatted by nbQA"
        git push

         

        
